StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController :Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
			ViewData["Title"] = "Categories";
			var model =  _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
	public class OrderController : Controller
	{
		private readonly IServiceManager _manager;
		private readonly Cart _cart;

		public OrderController(IServiceManager manager, Cart cart)
		{
			_manager = manager;
			_cart = cart;
		}
		[Authorize]
		public ViewResult Checkout() => View(new Order());

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Checkout([FromForm]Order order)
		{
			if(_cart.Lines.Count()==0)
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}

			if(ModelState.IsValid)
			{
				order.Lines = _cart.Lines.ToArray();
				_manager.OrderService.SaveOrder(order);
				_cart.Clear();
				return RedirectToPage("/Complete", new { OrderId = order.OrderId });
			}
			else
			{
				return View();
			}
		}
	}
}

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreApp - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header", false)

    </header>
    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
	<div class="container">
		<a class="navbar-brand" href="">Admin <i class="fa-solid fa-screwdriver-wrench"></i></a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
				aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
			<ul class="navbar-nav flex-grow-1">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Dashboard"
					   asp-action="Index">
						Dashboard
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Product"
					   asp-action="Index">
						Products(@await Component.InvokeAsync("ProductSummary"))
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Category" asp-action="Index">
						Categories
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Order" asp-action="Index">
						Orders
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="Role" asp-action="Index">
						Roles
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" asp-controller="User" asp-action="Index">
						Users
					</a>
			</ul>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a target="_blank" class="nav-link text-white" aria-current="page" asp-area="" asp-controller="Home"
					   asp-action="Index">
						<i class="fa fa-solid fa-search"></i>
						Web
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-white" aria-current="page" asp-area="" asp-controller="Account"
					   asp-action="Logout">
						<i class="fa-solid fa-right-from-bracket"></i>
						Logout
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>